server:
  port: 8081

spring:
  application:
    name: ai
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  data:
    redis:
      database: 1
      host: 192.168.209.128
      port: 6379
    mongodb:
      host: 192.168.209.128
      port: 27017
      database: botDB
      username: root
      password: example
      authentication-database: admin
    milvus:
      url: ${MILVUS_URL:http://192.168.209.128:19530}
      host: ${MILVUS_HOST:192.168.209.128}
      port: ${MILVUS_PORT:19530}
      defaultDatabaseName: ${MILVUS_DEFAULT_DATABASE:default}
      defaultCollectionName: ${MILVUS_DEFAULT_COLLECTION:novelCollection}
  servlet:
    multipart:
      max-file-size: 20MB
  neo4j:
    uri: bolt://192.168.209.128:7687
    authentication:
      username: neo4j
      password: password

langchain4j:
  models:
    gemini:
      apiKey: ${GEMINI_API_KEY}
      modelName: gemini-2.0-flash
      temperature: 0.7
    qwen:
      apiKey: ${QWEN_API_KEY}
      location: us-central1
      modelName: text-embedding-v2
    ollama:
      url: http://localhost:11434
      modelName: gemma3:12b
      temperature: 0.3
      timeout: 600000
    minimax:
      baseUrl: https://api.minimaxi.com/v1
      apiKey: sk-cp-IESO6g5_bhrqDylthjt8e6t5ovc6Tml9FpOAKAMsnns0q5tbotk-kh-1N5UlSBZ-rsXCPo1mt3zE5igkx--mEylFzdaHH6bW1T8vv3uGHi_OkBLycKCY2rY
      modelName: MiniMax-M2.5
      temperature: 0.7

milvus:
  uri: http://192.168.209.128:19530
  username: ${MILVUS_USERNAME:}
  password: ${MILVUS_PASSWORD:}
  db-name: ${MILVUS_DATABASE:default}
  message-collection-name: ${MILVUS_COLLECTION:chatEmbeddingCollection}
  top-k: 5
